#! /usr/bin/env sh
# This script is based on Rich Felker's install.sh from musl libc and is
# considered public domain.
# -----------------------------------------------------------------------------

set -e

ai_help="\
usage: ${0##*/} [-Dlr] [-m <mode>] <src> <dst>

Install <source> atomically to <dest>.

Options:
 -D           Create all parent directories.
 -h           Print this help text.
 -l           Install as a symbolic link.
 -m <mode>    Use file mode <mode> for <dst> instead of the default 0755.
 -r           Install as a relative symbolic link.
"

fatal()
{
	_fatal_fmt="${1}"
	shift

	# shellcheck disable=SC2059
	printf "fatal: ${_fatal_fmt}\\n" "${@}" >&2
	exit 126
}

modecheck()
{
	_mc_i=0

	for _mc_c in $(printf "%s" "${1}" | sed 's/./& /g'); do
		case "${_mc_c}" in
		[0-7])
			;;
		*)
			return 1
			;;
		esac

		_mc_i="$((_mc_i + 1))"
	done

	if [ "${_mc_i}" -gt 4 ]; then
		return 1
	fi

	return 0
}

relative()
{
	# ${1} MUST exist already
	# The parent directory of ${2} MUST exist already

	if [ ! -e "${1}" ]; then
		fatal "does not exist: %s" "${1}"
	fi

	if [ ! -d "${2%/*}/" ]; then
		fatal "directory does not exist: %s" "${2%/*}/"
	fi

	_rel_src="$(realpath "${1}")"
	_rel_dst="$(realpath "${2}")"

	_rel_com="${_rel_dst%/*}/"
	_rel_up=""

	while [ "${_rel_src#${_rel_com}}" = "${_rel_src}" ]; do
		_rel_com="${_rel_com%/*/}/"
		_rel_up="../${_rel_up}"
	done

	printf "%s" "${_rel_up}${_rel_src#${_rel_com}}"
}

ai_mkdirp="n"
ai_mode="0755"
ai_symlink="n"
ai_symlink_rel="n"

while getopts ":Dhlm:r" opt; do
	case "${opt}" in
	D)
		ai_mkdirp="y"
		;;
	h)
		printf "%s\\n" "${ai_help}"
		exit 0
		;;
	l)
		ai_symlink="y"
		;;
	m)
		if ! modecheck "${OPTARG}"; then
			fatal "invalid mode: %s" "${OPTARG}"
		fi

		ai_mode="${OPTARG}"
		;;
	r)
		ai_symlink="y"
		ai_symlink_rel="y"
		;;
	:)
		fatal "option requires argument: -%s" "${OPTARG}"
		;;
	*)
		fatal "unknown option: -%s" "${OPTARG}"
		;;
	esac
done
shift $((OPTIND - 1))

if [ "${#}" -ne 2 ]; then
	fatal "two arguments required: <src> <dst>"
fi

src="${1}"
dst="${2}"
tmp="${dst}.tmp.${$}"

if [ -z "${dst##*/}" ]; then
	fatal "<dst> ends with '/': %s" "${dst}"
fi

if [ "${ai_mkdirp}" = "y" ] && [ -n "${dst%/*}" ]; then
	umask 022
	mkdir -p "${dst%/*}"
fi

set -C
umask 077
trap 'rm -rf ${tmp}' EXIT HUP INT QUIT TERM

if [ "${ai_symlink}" = "y" ]; then
	if [ "${ai_symlink_rel}" = "y" ]; then
		ln -s "$(relative "${src}" "${tmp}")" "${tmp}"
	else
		ln -s "${src}" "${tmp}"
	fi
else
	cp "${src}" "${tmp}"
	chmod "${ai_mode}" "${tmp}"
fi

if [ -d "${dst}" ]; then
	fatal "<dst> is a directory: %s" "${dst}"
fi

mv -f "${tmp}" "${dst}"
